version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  database: