version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    command: uvicorn main:application --host 0.0.0.0
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  database: