version: '3.8'

networks:
  quiz_network:
    driver: bridge

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=quiz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - PG_DB_URL=postgresql+asyncpg://
    networks:
      - quiz_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - URL=https://jservice.io/api/random?count=1
    networks:
      - quiz_network

volumes:
  database: