version: '3.8'

networks:
  quiz_network:
    driver: bridge

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - quiz_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - quiz_network

volumes:
  database: